### ISSUE TITLE
edit on related records

### ISSUE THREAD

**Issue by Jfeger310** [effordDev/sf-application#3]
Can we have an edit on the related lists records? that puts that records field data back into the enter fields, then I can edit then re-save it?  Use case; I could pre-create the first household member upon create of application with the applicant contact, being the first household member, but they’d need to edit to fill in the Income, or any other field we still need?

**Comment by effordDev** [comment]
@Jfeger310 This would be related to a custom component. This functionality doesn't live here, but yes can do.
