### ISSUE TITLE
Save some fields

### ISSUE THREAD

**Issue by Jfeger310** [effordDev/sf-application#4]
Can I still save the section leaving required fields blank, but it not allows the section to b complete.  So I can do part of the app, then come back and finish, but it saved the part I did earlier?

**Comment by effordDev** [comment]
We can, maybe configurable by the Reference_Application_Section__c? Allow_Partial_Save__c  - would allow users to save the section even if required fields are not completed.

**Comment by Jfeger310** [comment]
Yes!  I like it!

**Comment by effordDev** [comment]
@Jfeger310 is the the ability to use dependent picklists as parent questions and show/hide child questions #13 suffice to closing this?

**Comment by Jfeger310** [comment]
I'm good with it
