### ISSUE TITLE
Flows not read only after 

### ISSUE THREAD

**Issue by Jfeger310** [effordDev/sf-application#70]
After application is submitted, and we make the read only true, users can still run through flow?  anyway to have th input flow also follow the read only?  I know that we can do this on the flow as a decision but it would be cool it if followed the package design

**Comment by effordDev** [comment]
@Jfeger310 this needs to be handled via flow configuration. Flow should have the `Application__c.Id` context passed in as `recordId`. The flow can check the status and render appropriately.
